### ISSUE TITLE
Optional logging.appenders[0].tag Has Multiple Matching Constraint Validators

### ISSUE THREAD

**Issue by MusikPolice** [reines/dropwizard-logging-loggly#5]
I'm trying to use dropwizard-logging-loggly:0.6 with dropwizard-core:0.9.1, and I can't get my server to start. Here's my config:
```
logging:
    level: INFO
    appenders:
        - type: loggly
          token: "..."
```
When I try to start the application, I get this error:
```
Exception in thread "main" javax.validation.UnexpectedTypeException: HV000186: The constraint of type 'javax.validation.constraints.NotNull' defined on 'logging.appenders[0].tag' has multiple matching constraint validators which is due to an additional value handler of type 'io.dropwizard.validation.valuehandling.OptionalValidatedValueUnwrapper'. It is unclear which value needs validating. Clarify configuration via @UnwrapValidatedValue.
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.getConstraintValidatorInstanceForAutomaticUnwrapping(ConstraintTree.java:266)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.getInitializedConstraintValidator(ConstraintTree.java:163)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:116)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:87)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:73)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:592)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraint(ValidatorImpl.java:555)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:490)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:454)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:406)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraint(ValidatorImpl.java:770)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraints(ValidatorImpl.java:656)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:415)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraint(ValidatorImpl.java:770)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraints(ValidatorImpl.java:656)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:415)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:204)
	at io.dropwizard.configuration.ConfigurationFactory.validate(ConfigurationFactory.java:257)
	at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:149)
	at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:95)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:115)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:64)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:80)
	at com.aeryon.live.WebServiceApplication.main(WebServiceApplication.java:40)
```
The issue appears to be with the combination of the @NotNull annotation and the Optional<String> type on line 78 of LogglyAppenderFactory.class, but I'm quite new to Dropwizard so I can't say for sure.

**Comment by reines** [comment]
I believe this must be related to some changes within Dropwizard. This appender was written for Dropwizard 0.7.x, and I'm afraid has not been updated or tested against 0.9.x yet.

I'm more than happy to accept pull requests for fixes, but I'm unlikely to get around to updating it myself anytime soon I'm afraid :disappointed:

**Comment by gauravspatel** [comment]
Pull request inbound.

**Comment by edouardswiac** [comment]
@reines I can see the code is in master but it's a snapshot. Any change you can cut a release? thanks!

**Comment by reines** [comment]
I've just pushed 0.7 to Maven Central, it should appear within a few hours. Please let me know if it doesn't.

**Comment by edouardswiac** [comment]
thanks for the quick answer!
